# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='qq',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
